on:
  push:
    branches:
      [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run script
        run: echo Hello, World!
      - name: Set JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Compile
        run: javac src/main/java/ca/dobbs/App.java
      - name: Run Java
        run: java -cp src/main/java/ ca.dobbs.App
      - name: Build with Maven
        run: mvn compile
      - name: Run Tests
        run: mvn test
      - name: Run Application
        run: mvn exec:java -Dexec.mainClass="ca.dobbs.App"
